  apiVersion: v1
  kind: Service
  metadata:
    name: gdsc-login
  spec:
    selector:
      app: gdsc-login
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

        
